export interface ErrorCatalogEntry {
  readonly code: string;
  readonly httpStatus: number;
  readonly category:
    'AUTH' | 'IAM' | 'VALIDATION' | 'STORAGE' | 'CONCURRENCY' | 'CHANNEL' | 'MESSAGING' | 'SYSTEM';
  readonly description: string;
  readonly safeClientMessage: string;
  readonly actionableGuidance: string;
}

/**
 * Canonical catalog of machine-readable error codes (FND-BE-010, FND-037).
 */
export const ERROR_CATALOG: readonly ErrorCatalogEntry[] = [
  {
    code: 'BAD_REQUEST',
    httpStatus: 400,
    category: 'VALIDATION',
    description: 'The request syntax is invalid or required HTTP headers are missing.',
    safeClientMessage: 'The request could not be processed due to invalid syntax.',
    actionableGuidance: 'Check request syntax, headers, and query parameters before retrying.',
  },
  {
    code: 'AUTH_TOKEN_MISSING',
    httpStatus: 401,
    category: 'AUTH',
    description: 'No Bearer token was provided in the Authorization header.',
    safeClientMessage: 'Authentication credentials are required to access this resource.',
    actionableGuidance: 'Provide a valid Supabase access token in the Authorization header.',
  },
  {
    code: 'AUTH_TOKEN_INVALID',
    httpStatus: 401,
    category: 'AUTH',
    description: 'The supplied JWT token failed signature verification or has expired.',
    safeClientMessage: 'The provided access token is invalid or expired.',
    actionableGuidance: 'Refresh the access token via Supabase Auth and retry the request.',
  },
  {
    code: 'USER_PROFILE_INACTIVE',
    httpStatus: 403,
    category: 'IAM',
    description: 'The user account has been disabled or deactivated.',
    safeClientMessage: 'Your user account is inactive. Contact your workspace administrator.',
    actionableGuidance: 'Contact workspace admin or customer support to reactivate the account.',
  },
  {
    code: 'WORKSPACE_MEMBERSHIP_NOT_FOUND',
    httpStatus: 403,
    category: 'IAM',
    description: 'The authenticated user does not belong to the requested workspace.',
    safeClientMessage: 'You do not have access to the requested workspace.',
    actionableGuidance: 'Verify the x-workspace-id header or request an invitation to join.',
  },
  {
    code: 'WORKSPACE_MEMBERSHIP_INACTIVE',
    httpStatus: 403,
    category: 'IAM',
    description: 'The user membership in this workspace has been suspended or deleted.',
    safeClientMessage: 'Your workspace membership is suspended or removed.',
    actionableGuidance: 'Contact your workspace administrator to restore membership.',
  },
  {
    code: 'PERMISSION_DENIED',
    httpStatus: 403,
    category: 'IAM',
    description: 'The actor lacks one or more required permissions for this action.',
    safeClientMessage: 'Forbidden: Insufficient permissions to perform this operation.',
    actionableGuidance: 'Request role assignment with the missing permission(s) listed in details.',
  },
  {
    code: 'RESOURCE_NOT_FOUND',
    httpStatus: 404,
    category: 'SYSTEM',
    description: 'The requested resource does not exist.',
    safeClientMessage: 'The requested resource was not found.',
    actionableGuidance: 'Verify the resource identifier in the URL path.',
  },
  {
    code: 'ATTACHMENT_NOT_FOUND',
    httpStatus: 404,
    category: 'STORAGE',
    description: 'The requested attachment does not exist within the active workspace.',
    safeClientMessage: 'The requested attachment does not exist in this workspace.',
    actionableGuidance: 'Verify attachment ID and workspace context.',
  },
  {
    code: 'IDEMPOTENCY_KEY_REUSED',
    httpStatus: 409,
    category: 'CONCURRENCY',
    description: 'An idempotency key was reused with a different request payload or method.',
    safeClientMessage: 'Idempotency key was previously used with different request parameters.',
    actionableGuidance: 'Generate a new UUIDv7 / unique idempotency key for new mutations.',
  },
  {
    code: 'IDEMPOTENCY_IN_FLIGHT',
    httpStatus: 409,
    category: 'CONCURRENCY',
    description: 'A request with the specified idempotency key is currently being executed.',
    safeClientMessage: 'A request with this idempotency key is currently processing.',
    actionableGuidance: 'Wait for the current operation to complete before retrying.',
  },
  {
    code: 'ATTACHMENT_EXPIRED',
    httpStatus: 410,
    category: 'STORAGE',
    description: 'The attachment has exceeded its retention policy and was purged.',
    safeClientMessage: 'Attachment has expired and has been permanently purged.',
    actionableGuidance: 'Expired attachments cannot be recovered.',
  },
  {
    code: 'ATTACHMENT_DELETED',
    httpStatus: 410,
    category: 'STORAGE',
    description: 'The attachment was soft-deleted by an agent or user.',
    safeClientMessage: 'Attachment has been deleted.',
    actionableGuidance: 'Contact workspace admin if restoration is needed.',
  },
  {
    code: 'VALIDATION_FAILED',
    httpStatus: 422,
    category: 'VALIDATION',
    description: 'The request body or parameters failed schema validation rules.',
    safeClientMessage: 'Request validation failed on one or more fields.',
    actionableGuidance: 'Inspect details.issues array for field-level error messages.',
  },
  {
    code: 'ATTACHMENT_NOT_CLEAN',
    httpStatus: 422,
    category: 'STORAGE',
    description: 'The attachment is undergoing malware scanning or was flagged as infected.',
    safeClientMessage: 'Attachment is not clean or malware scan is pending/failed.',
    actionableGuidance: 'Wait for scan completion. Infected files are blocked permanently.',
  },
  {
    code: 'ATTACHMENT_QUARANTINED',
    httpStatus: 422,
    category: 'STORAGE',
    description: 'The attachment is currently in the quarantine storage zone.',
    safeClientMessage: 'Attachment is currently quarantined and cannot be downloaded.',
    actionableGuidance: 'Quarantined attachments must be validated before access is granted.',
  },
  {
    code: 'DEV_USER_NOT_FOUND',
    httpStatus: 404,
    category: 'AUTH',
    description: 'Development sign-in: no active seeded user with that email.',
    safeClientMessage: 'No development user with this email exists.',
    actionableGuidance:
      'Run the database seed, or sign in as a user it created (admin@vynor.local).',
  },
  {
    code: 'CHANNEL_NOT_FOUND',
    httpStatus: 404,
    category: 'CHANNEL',
    description: 'The channel does not exist in this workspace or was deleted.',
    safeClientMessage: 'This channel could not be found.',
    actionableGuidance: 'Refresh the channel list; it may have been deleted.',
  },
  {
    code: 'CHANNEL_VERIFICATION_FAILED',
    httpStatus: 422,
    category: 'CHANNEL',
    description: 'The provider rejected the credentials or account configuration while connecting.',
    safeClientMessage: 'The platform rejected these credentials.',
    actionableGuidance:
      'Compare the values with the provider console and try again; the message repeats what the provider reported.',
  },
  {
    code: 'CHANNEL_PROVIDER_UNREACHABLE',
    httpStatus: 502,
    category: 'CHANNEL',
    description: 'The provider API did not answer or timed out while verifying the connection.',
    safeClientMessage: 'The platform could not be reached.',
    actionableGuidance: 'Retry shortly and check that the API has outbound internet access.',
  },
  {
    code: 'CHANNEL_ALREADY_CONNECTED',
    httpStatus: 409,
    category: 'CHANNEL',
    description: 'The same provider account is already connected in this workspace.',
    safeClientMessage: 'This account is already connected.',
    actionableGuidance: 'Use the existing channel, or delete it before connecting again.',
  },
  {
    code: 'CHANNEL_ACCOUNT_MISMATCH',
    httpStatus: 409,
    category: 'CHANNEL',
    description:
      'New credentials belong to a different provider account than the channel being updated.',
    safeClientMessage: 'These credentials belong to a different account.',
    actionableGuidance:
      'Enter credentials for the same account, or connect the other account as a new channel.',
  },
  {
    code: 'CHANNEL_PROVIDER_MISMATCH',
    httpStatus: 422,
    category: 'CHANNEL',
    description: 'The submitted credentials are for a different platform than the channel.',
    safeClientMessage: 'These credentials are for a different platform.',
    actionableGuidance: 'Update the channel with credentials for its own platform.',
  },
  {
    code: 'CHANNEL_PROVIDER_UNSUPPORTED',
    httpStatus: 422,
    category: 'CHANNEL',
    description: 'No adapter is available for the requested provider.',
    safeClientMessage: 'This platform is not supported.',
    actionableGuidance: 'Choose one of the platforms listed in the connect dialog.',
  },
  {
    code: 'CHANNEL_ENDPOINT_NOT_ALLOWED',
    httpStatus: 422,
    category: 'CHANNEL',
    description:
      'A mail server or endpoint URL resolves to a private or otherwise disallowed network address.',
    safeClientMessage: 'This server address is not allowed.',
    actionableGuidance:
      'Use a public host name; private addresses are blocked in staging and production.',
  },
  {
    code: 'CREDENTIAL_ENCRYPTION_NOT_CONFIGURED',
    httpStatus: 503,
    category: 'CHANNEL',
    description:
      'ENCRYPTION_MASTER_KEY is not set, so channel credentials cannot be stored or read.',
    safeClientMessage: 'Channels cannot be connected until encryption is configured.',
    actionableGuidance:
      'Set ENCRYPTION_MASTER_KEY (openssl rand -base64 32) on the API and worker, then restart them.',
  },
  {
    code: 'INVALID_HUMAN_AGENTS',
    httpStatus: 422,
    category: 'CHANNEL',
    description: 'One or more selected human agents are not active members of the workspace.',
    safeClientMessage: 'Some selected agents are not active members.',
    actionableGuidance: 'Pick agents from the current member list.',
  },
  {
    code: 'WIDGET_NOT_FOUND',
    httpStatus: 404,
    category: 'CHANNEL',
    description: 'The web chat widget key is unknown or its channel was deleted.',
    safeClientMessage: 'This chat is not available.',
    actionableGuidance: 'Copy the current embed snippet from the channel settings.',
  },
  {
    code: 'VISITOR_TOKEN_INVALID',
    httpStatus: 401,
    category: 'CHANNEL',
    description: 'The web chat visitor token is missing, expired or was issued for another widget.',
    safeClientMessage: 'Your chat session expired.',
    actionableGuidance: 'The widget starts a new session automatically.',
  },
  {
    code: 'CONVERSATION_NOT_FOUND',
    httpStatus: 404,
    category: 'MESSAGING',
    description: 'The conversation does not exist in this workspace.',
    safeClientMessage: 'This conversation could not be found.',
    actionableGuidance: 'Refresh the Inbox.',
  },
  {
    code: 'MESSAGE_NOT_FOUND',
    httpStatus: 404,
    category: 'MESSAGING',
    description: 'The message does not exist in this workspace.',
    safeClientMessage: 'This message could not be found.',
    actionableGuidance: 'Refresh the conversation.',
  },
  {
    code: 'MESSAGE_NOT_RETRYABLE',
    httpStatus: 409,
    category: 'MESSAGING',
    description: 'Only failed outbound replies can be retried.',
    safeClientMessage: 'This message cannot be retried.',
    actionableGuidance: 'Retry only replies marked as failed.',
  },
  {
    code: 'CHANNEL_DELETED',
    httpStatus: 409,
    category: 'MESSAGING',
    description: "Replies cannot be sent because the conversation's channel was deleted.",
    safeClientMessage: 'This channel was deleted, so replies cannot be sent.',
    actionableGuidance: 'Connect the account again to continue the conversation.',
  },
  {
    code: 'CHANNEL_NEEDS_RECONNECT',
    httpStatus: 409,
    category: 'MESSAGING',
    description: "Replies are blocked until the channel's credentials are updated.",
    safeClientMessage: 'This channel needs to be reconnected.',
    actionableGuidance: 'Update the channel credentials in Channels, then retry the reply.',
  },
  {
    code: 'INVALID_ASSIGNEE',
    httpStatus: 422,
    category: 'MESSAGING',
    description: 'The selected assignee is not an active member of the workspace.',
    safeClientMessage: 'This person cannot be assigned.',
    actionableGuidance: 'Choose an active workspace member.',
  },
  {
    code: 'INVALID_REPLY_TARGET',
    httpStatus: 422,
    category: 'MESSAGING',
    description: 'The message being replied to is not part of this conversation.',
    safeClientMessage: 'The quoted message is not in this conversation.',
    actionableGuidance: 'Reply to a message from the same conversation.',
  },
  {
    code: 'RATE_LIMITED',
    httpStatus: 429,
    category: 'SYSTEM',
    description: 'Too many requests were sent in a given time window.',
    safeClientMessage: 'Rate limit exceeded. Please back off before retrying.',
    actionableGuidance: 'Respect the Retry-After header and implement exponential backoff.',
  },
  {
    code: 'INTERNAL_SERVER_ERROR',
    httpStatus: 500,
    category: 'SYSTEM',
    description: 'An unexpected internal error occurred on the server.',
    safeClientMessage: 'An unexpected internal server error occurred.',
    actionableGuidance: 'Quote the x-correlation-id when contacting technical support.',
  },
  {
    code: 'SERVICE_UNAVAILABLE',
    httpStatus: 503,
    category: 'SYSTEM',
    description: 'A required downstream service or database is temporarily unavailable.',
    safeClientMessage: 'Service temporarily unavailable. Please retry shortly.',
    actionableGuidance: 'Check service status and retry with jittered exponential backoff.',
  },
];
